// <auto-generated />
using BaiTap.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BaiTap.Data.Migrations
{
    [DbContext(typeof(databaseContext))]
    partial class databaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BaiTap.Data.Entities.Class", b =>
                {
                    b.Property<int>("IdClass")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdClass");

                    b.ToTable("Class");

                    b.HasData(
                        new
                        {
                            IdClass = 1,
                            ClassName = "IT"
                        },
                        new
                        {
                            IdClass = 2,
                            ClassName = "Du Lịch"
                        },
                        new
                        {
                            IdClass = 3,
                            ClassName = "Thiết Kế Đồ Hoạ"
                        });
                });

            modelBuilder.Entity("BaiTap.Data.Entities.Student", b =>
                {
                    b.Property<int>("IdStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailStudent")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdClass")
                        .HasColumnType("int");

                    b.Property<double>("Mark")
                        .HasColumnType("float");

                    b.Property<string>("NameStudent")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdStudent");

                    b.HasIndex("IdClass");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            IdStudent = 1,
                            EmailStudent = "manhldph10164@fpt.edu.vn",
                            IdClass = 1,
                            Mark = 8.0,
                            NameStudent = "Mạnh"
                        },
                        new
                        {
                            IdStudent = 2,
                            EmailStudent = "luongtuan@gmail.com",
                            IdClass = 1,
                            Mark = 9.0,
                            NameStudent = "Tuấn"
                        });
                });

            modelBuilder.Entity("BaiTap.Data.Entities.Student", b =>
                {
                    b.HasOne("BaiTap.Data.Entities.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("IdClass")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("BaiTap.Data.Entities.Class", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
